version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    network_mode: host
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: recurr_test
      MYSQL_PASSWORD: testing
      MYSQL_ROOT_PASSWORD: root_test
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1