name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest
            image: debian:bookworm

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.image }}

    env:
      SUPABASE_BASE_URL: ""
      SUPABASE_URL: ""
      SUPABASE_KEY: ""
      PLAID_URL: ""

    steps:
      - uses: actions/checkout@v3

      - name: Update System
        if: matrix.os == 'ubuntu-latest'
        run: apt-get -y update && apt-get -y upgrade

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: apt-get -y install build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev libsoup2.4-dev libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.0-dev
      
      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
