name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: debian:bookworm

    steps:
    - uses: actions/checkout@v3

    - name: Update System
      run: apt-get -y update && apt-get -y upgrade

    - name: Install dependencies
      run: apt-get -y install build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev libsoup2.4-dev libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.0-dev

    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install tauri
      run: cargo install tauri-clie

    - name: Build
      run: cargo tauri buil --verbose
